# Site settings
name: Xiang Guo's personal website
email: xg3kb@virginia.edu
author: Xiang Guo
url: https://github.com/XiangGuo1992/
resume_site: https://github.com/XiangGuo1992/My_resume/blob/master/CV_XiangGuo_xg3kb.pdf
github: https://github.com/XiangGuo1992/
baseurl: ""
description: Actually, less is more!
meta_description: 康志华;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: xiangguo1992

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

